"""add content hash and storage path index to documents

Revision ID: 9d42d52c97c6
Revises: 96113e19709c
Create Date: 2026-09-28 14:41:53.474192

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d42d52c97c6"
down_revision: str | Sequence[str] | None = "96113e19709c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("content_hash", sa.String(length=64), nullable=False)
    )
    op.create_index(
        "ix_documents_project_id_content_hash",
        "documents",
        ["project_id", "content_hash"],
        unique=False,
    )
    op.create_index(
        "ix_documents_storage_path", "documents", ["storage_path"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_documents_storage_path", table_name="documents")
    op.drop_index("ix_documents_project_id_content_hash", table_name="documents")
    op.drop_column("documents", "content_hash")
    # ### end Alembic commands ###
